# Default values for template.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: sprysio/efarm-frontend
  pullPolicy: IfNotPresent
  tag: develop-2b002009363013443edd9c862ffa1ce71e2fdb87

service:
  type: LoadBalancer
  port: 80

resources:
  limits:
     cpu: 100m
     memory: 128Mi

ingress:
  apiName: efarm-backend-svc

livenessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 60
  periodSeconds: 60
readinessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 60
  periodSeconds: 60
