apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: frontend

images:
  - name: sprysio/efarm-frontend
    newTag: develop-d08dadfec96db39d1c3341a16503efd6cfc41464
