name: Pull request to dev branch CI

on:
  pull_request:
    branches:
      - 'develop'

jobs:
  secret-scanning:
    if: |
      startsWith(github.head_ref, 'feature/') || 
      startsWith(github.head_ref, 'bugfix/')
    name: Secret Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Secret Scanning
        uses: secret-scanner/action@0.0.2

  lint-scan-unit:
    if: |
      startsWith(github.head_ref, 'feature/') || 
      startsWith(github.head_ref, 'bugfix/')
    name: Lint, Scan and Unit Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    
    - name: Cache Node.js modules
      id: cache-npm
      uses: actions/cache@v4
      with:
        path: ~/.npm 
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
        
    - name: Install dependencies
      run: npm ci

    - name: Lint code
      run: npm run lint

    - name: Run security audit
      run: npm audit --audit-level=high

    - name: Build React app
      run: npm run build
    
