name: Secret scanning and Lint on feature/ branch

on:
  push:
    branches:
      - 'feature/*'
      - 'bugfix/*'

jobs:
  secret-scanning:
    name: Secret Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Secret Scanning
        uses: secret-scanner/action@0.0.2

  lint-scan:
    name: Lint, Scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    
    - name: Restore Node.js modules
      uses: actions/cache/restore@v4
      with:
        path: ~/.npm 
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
        
    - name: Install dependencies
      run: npm ci

    - name: Lint code
      run: npm run lint

    - name: Run security audit
      run: npm audit --audit-level=high

    - name: Build React app
      run: npm run build
    
